### PR TITLE
fix: add peer dep pact-js v11 and nest-js v10

### PR DESCRIPTION
**Pull request by JoffrayBillon**
Add Nest 10 and Pact 11 support

## Description
As there is no impacting changes with the Nest 10 and Pact 11 releases for this package change the peerDependencies, to allow nest 10 to be used as a peer dependancy.
Also changed the fixed v10 pact version to any v10 and v11 (ok for v11 as I said before)

## Motivation and Context
Make the package work for NestJS recent release 10 on `npm install` without error `Conflicting peer dependency`.

## How Has This Been Tested?
In my fork branch of the `nestjs-pact` project:
```
npm run build
npm pack --pack-destination ~
```
Then in the "final project" I try `npm install` after replacing in the `package.json`:
```
"nestjs-pact": "^2.3.0",
```
With
```
"nestjs-pact": "file:~/nestjs-pact-2.3.1.tgz",
```
Check if installation pass, looks good, good to go.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by YOU54F** [comment]
Thanks for the PR, it is very odd that it triggered the workflows automatically however, as our settings as meant to prevent that

Screenshot 2023-07-07 at 10 32 00

**Comment by YOU54F** [comment]
Oh I can see Matt triggered it :) Will take a look at the errors today

**Comment by YOU54F** [comment]
Hey, if you could update the commit messages, to follow the commit convention as suggested by the latest error message. we will get a green build 👍🏾 

[fix: add peer dep pact-js v11 and nest-js v10](https://github.com/pact-foundation/nestjs-pact/pull/48/commits/16aaccd00879e589da858615c7bb6d52141f2838)

**Comment by YOU54F** [comment]
I'll leave this with you so you can get attribution rather than merging the draft PR I created for testing. Cheers buddy

**Comment by JoffrayBillon** [comment]
I changed but only for the latest message show i change for all the messages ?

**Pull request merged**
